#
# Peter R. Elespuru
#
# This makefile is for Linux (uname = 'Linux'), and should
# be automatically called by the main makefile on that platform.
# If that doesn't work, it can be used directly too via make -f Makefile.Linux
#
all: 
	gcc -Wall -O3 -o cvglsl *.c -lglut -lGLU -lopencv_core -lopencv_contrib -lopencv_flann -lopencv_features2d -lopencv_highgui -lopencv_imgproc -lopencv_gpu

#
###  Clean up
#
clean:
	rm -f cvglsl
